---
title: "About the Shiny"
output: html_document
---


## About the Shiny

Quisque in dictum sem, non mattis quam. Nunc tempor enim ante, ut aliquet justo pretium vel. Ut facilisis massa euismod ex faucibus efficitur. Nam id volutpat velit. Proin ultricies augue et odio auctor tempus. Nullam mauris erat, laoreet at mauris ac, mollis tristique nisl. Morbi quis odio posuere, efficitur ex ac, fringilla mi. Vivamus nulla mi, interdum at massa sed, dictum scelerisque quam. Aliquam euismod mi ut magna iaculis pretium. Aliquam sed augue neque. Suspendisse vitae imperdiet erat. In maximus nulla feugiat lacinia vehicula. Duis tincidunt nunc ligula, vehicula bibendum turpis tristique at. Phasellus est dolor, luctus tincidunt tempor at, venenatis id ante. Morbi ante nunc, ullamcorper auctor nulla accumsan, dictum laoreet magna. 


[The Link to the Systematic Review](https://systematicreviewsjournal.biomedcentral.com/articles/10.1186/s13643-017-0465-z)


## Definitions and Terminologies

Quisque in dictum sem, non mattis quam. Nunc tempor enim ante, ut aliquet justo pretium vel. Ut facilisis massa euismod ex faucibus efficitur. Nam id volutpat velit. Proin ultricies augue et odio auctor tempus. Nullam mauris erat, laoreet at mauris ac, mollis tristique nisl. Morbi quis odio posuere, efficitur ex ac, fringilla mi. Vivamus nulla mi, interdum at massa sed, dictum scelerisque quam. Aliquam euismod mi ut magna iaculis pretium. Aliquam sed augue neque. Suspendisse vitae imperdiet erat. In maximus nulla feugiat lacinia vehicula. Duis tincidunt nunc ligula, vehicula bibendum turpis tristique at. Phasellus est dolor, luctus tincidunt tempor at, venenatis id ante. Morbi ante nunc, ullamcorper auctor nulla accumsan, dictum laoreet magna. 

* Curabitur in ante ornare, tincidunt purus non, ornare turpis. Integer nec consequat sapien. Vivamus ut eros nec ligula sollicitudin porta et at nisl. Suspendisse lacinia consectetur consequat. Nam in feugiat quam, rhoncus interdum urna. Etiam ultricies suscipit elit, nec vulputate tortor fermentum sed. Sed at pulvinar lectus.

* Curabitur in ante ornare, tincidunt purus non, ornare turpis. Integer nec consequat sapien. Vivamus ut eros nec ligula sollicitudin porta et at nisl. Suspendisse lacinia consectetur consequat. Nam in feugiat quam, rhoncus interdum urna. Etiam ultricies suscipit elit, nec vulputate tortor fermentum sed. Sed at pulvinar lectus.

* Curabitur in ante ornare, tincidunt purus non, ornare turpis. Integer nec consequat sapien. Vivamus ut eros nec ligula sollicitudin porta et at nisl. Suspendisse lacinia consectetur consequat. Nam in feugiat quam, rhoncus interdum urna. Etiam ultricies suscipit elit, nec vulputate tortor fermentum sed. Sed at pulvinar lectus.